{{- if .Values.variables.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airbnb-server.fullname" . }}
  labels:
    {{- include "airbnb-server.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.variables.configmap | nindent 2}}
{{- end }}